strategies:
  - byzzfuzz
  - evo_partition

benchmarks:
  - aptos
  - bug1
  - bug3

block_height_max: 10

fitness:
  - execution_time
  - qc

max_parallel_workers: 4

population_size: 20
mu: 10 # Parent count (μ) for (μ+λ) selection in DEAP.
total_num_tests: 200 #0 # for evo, it's 2000/20=100 generations

max_partition_duration: 2000

num_nodes: 5
# other configs, eg. transactions ...
